In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('catalogs/yellowstone.amps.localmag.2023.mv5.csv')
df.head()

,Evid,Sta,Cmp,Net,ChanE,Loc,SMagTypeE,AmpE,UnE,SMLE,...,Event-Median-UUSSML-S,Station-YPML,Station-YPML-S,Event-Mean-YPML,Event-Median-YPML,Event-Mean-YPML-S,Event-Median-YPML-S,MwPref,SLUMw,UUSSMw
0,60000620.0,LKWY,BH,US,BHE,1.0,l,10.142061,mm,2.25,...,2.126877,2.070635,2.051707,2.040193,2.086396,2.069804,2.03058,NaN,NaN,NaN
1,60000620.0,YFT,HH,WY,HHE,1.0,l,1.636402,mm,1.94,...,2.126877,1.718287,1.902689,2.040193,2.086396,2.069804,2.03058,NaN,NaN,NaN
2,60000620.0,YUF,HH,WY,HHE,1.0,l,3.391413,mm,2.78,...,2.126877,2.293554,2.291645,2.040193,2.086396,2.069804,2.03058,NaN,NaN,NaN
3,60000620.0,YNR,HH,WY,HHE,1.0,l,2.132057,mm,2.47,...,2.126877,2.102157,2.161997,2.040193,2.086396,2.069804,2.03058,NaN,NaN,NaN
4,60000620.0,YMR,HH,WY,HHE,1.0,l,0.958534,mm,1.73,...,2.126877,2.103245,2.001331,2.040193,2.086396,2.069804,2.03058,NaN,NaN,NaN

In [3]:
ev_df = df.drop_duplicates(["Evid"])

In [4]:
print(f"There are {len(df)} amplitudes and {len(ev_df)} events in the YP21 ml catalog.")

There are 23613 amplitudes and 7651 events in the YP21 ml catalog.

In [5]:
ev_df.columns

Index(['Evid', 'Sta', 'Cmp', 'Net', 'ChanE', 'Loc', 'SMagTypeE', 'AmpE', 'UnE',
       'SMLE', 'SMLRes', 'Corr', 'SourceE', 'PerE', 'SnrE', 'EqLat', 'EqLon',
       'EqDepSL', 'EqOt', 'CatMag', 'CatMagType', 'Date', 'SLat', 'SLon',
       'SElev', 'ChanN', 'SMagTypeN', 'AmpN', 'UnN', 'SMLN', 'SourceN', 'PerN',
       'SnrN', 'EqDep', 'Repi', 'Rhyp', 'halfAmpH', 'Dmin', 'LOGA', 'LOGA0-YP',
       'LOGA0-UUSS', 'Sta-YP', 'Sj-YP', 'Sta-UUSS', 'Sj-UUSS',
       'Station-UUSSML', 'Station-UUSSML-S', 'Event-Mean-UUSSML',
       'Event-Median-UUSSML', 'Event-Mean-UUSSML-S', 'Event-Median-UUSSML-S',
       'Station-YPML', 'Station-YPML-S', 'Event-Mean-YPML',
       'Event-Median-YPML', 'Event-Mean-YPML-S', 'Event-Median-YPML-S',
       'MwPref', 'SLUMw', 'UUSSMw'],
      dtype='object')

In [6]:
# Only get columns useful for event information 
ev_df = ev_df[['Evid', 'EqLat', 'EqLon', 'EqDepSL', 'EqOt', 'CatMag', 'CatMagType', 'Date',
       'Event-Mean-YPML','Event-Median-YPML', 'Event-Mean-YPML-S', 'Event-Median-YPML-S']]

In [7]:
ev_df.head()

,Evid,EqLat,EqLon,EqDepSL,EqOt,CatMag,CatMagType,Date,Event-Mean-YPML,Event-Median-YPML,Event-Mean-YPML-S,Event-Median-YPML-S
0,60000620.0,44.474500,-110.552667,4.43,1.357546e+09,2.19,l,2013-01-07 08:12:32.649998+00:00,2.040193,2.086396,2.069804,2.030580
6,60000622.0,44.764500,-111.088000,7.69,1.349570e+09,0.83,l,2012-10-07 00:32:04.740000+00:00,0.717845,0.717845,0.694976,0.694976
8,60000940.0,44.479000,-110.591167,2.20,1.362430e+09,1.12,l,2013-03-04 20:50:17.969999+00:00,0.926021,0.926021,1.008759,1.008759
10,60000950.0,44.473500,-110.573333,-2.76,1.362431e+09,2.04,l,2013-03-04 21:02:42.149998+00:00,1.731116,1.778764,1.786967,1.799221
14,60000955.0,44.471833,-110.571000,4.69,1.362431e+09,2.06,l,2013-03-04 21:02:56.459999+00:00,1.847335,1.877622,1.901856,1.875712

In [8]:
ev_df.to_csv('catalogs/yellowstone.events.ypml-v5.2023.csv', index=False)