In [1]:
import pandas as pd
import numpy as np

In [ ]:
old_p_feats = pd.concat([pd.read_csv("../../data/old_features/p_features.csv"), pd.read_csv("../../data/old_features/p_features.2022.csv")])
old_p_feats

,arrival_identifier,avg_noise_1.00,avg_noise_10.00,avg_noise_11.00,avg_noise_12.00,avg_noise_13.00,avg_noise_14.00,avg_noise_15.00,avg_noise_16.00,avg_noise_17.00,...,signal_dominant_frequency,signal_maximum_value,signal_minimum_value,signal_variance,source_depth_km,source_latitude,source_longitude,source_receiver_back_azimuth,source_receiver_distance_km,station
0,2809,0.001365,0.001606,0.001186,0.000892,0.000699,0.000567,0.000471,0.000394,0.000327,...,6.0,2.255811,-1.575364,0.330048,7.69,44.764500,-111.088000,79.885217,8.701337,YHB
1,2829,0.005075,0.002426,0.002164,0.001883,0.001583,0.001299,0.001054,0.000852,0.000688,...,6.0,1.424917,-1.336169,0.164607,7.69,44.764500,-111.088000,62.981132,13.478685,YDC
2,2844,0.001299,0.001381,0.001291,0.001191,0.001077,0.000947,0.000811,0.000681,0.000565,...,4.0,0.794775,-0.656645,0.080753,7.69,44.764500,-111.088000,3.296971,17.661615,YWB
3,2869,0.000500,0.000243,0.000205,0.000175,0.000148,0.000124,0.000104,0.000087,0.000072,...,8.0,0.173261,-0.162381,0.003011,7.69,44.764500,-111.088000,6.698827,64.245602,MCID
4,4979,0.000562,0.003089,0.003346,0.003252,0.002937,0.002538,0.002137,0.001774,0.001463,...,6.0,3.011560,-4.218650,1.575028,14.30,44.389333,-111.035833,305.555989,22.657051,YPP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2535,3990809,0.008486,0.058925,0.061775,0.072467,0.085327,0.092437,0.092967,0.088749,0.082018,...,18.0,6.898986,-6.233131,3.025172,2.04,44.832667,-110.524167,50.234809,18.469212,YNM
2536,3990824,0.002835,0.001008,0.000906,0.000815,0.000720,0.000634,0.000575,0.000538,0.000514,...,4.0,2.314016,-2.254548,0.646173,2.04,44.832667,-110.524167,20.424922,26.965253,YML
2537,3990814,0.004662,0.000324,0.000308,0.000297,0.000288,0.000293,0.000320,0.000369,0.000426,...,7.0,0.229275,-0.308055,0.008482,2.04,44.832667,-110.524167,79.079524,26.280985,YHH
2538,3990844,0.000235,0.000695,0.000698,0.000637,0.000545,0.000449,0.000363,0.000292,0.000235,...,5.0,0.143471,-0.128406,0.002898,2.04,44.832667,-110.524167,77.768175,38.999234,YMC
2539,3990849,0.042469,0.001301,0.001025,0.000818,0.000660,0.000547,0.000481,0.000447,0.000424,...,1.0,0.242874,-0.281006,0.007511,2.04,44.832667,-110.524167,244.680768,45.153690,YNE

In [ ]:
new_p_feats = pd.read_csv("../../data/features/p_features.2024.csv")
new_p_feats

,event_identifier,arrival_identifier,network,station,channel,location_code,source_latitude,source_longitude,source_receiver_distance_km,source_receiver_back_azimuth,...,avg_noise_14.00,avg_signal_14.00,avg_noise_15.00,avg_signal_15.00,avg_noise_16.00,avg_signal_16.00,avg_noise_17.00,avg_signal_17.00,avg_noise_18.00,avg_signal_18.00
0,60000622,10000491,WY,YHB,EHZ,1,44.764500,-111.088000,8.701337,79.885217,...,0.000567,0.048452,0.000471,0.037601,0.000394,0.029268,0.000327,0.022911,0.000270,0.018074
1,60000622,10000495,WY,YDC,EHZ,1,44.764500,-111.088000,13.478685,62.981132,...,0.001299,0.029062,0.001054,0.022419,0.000852,0.017364,0.000688,0.013535,0.000557,0.010637
2,60000622,10000498,WY,YWB,EHZ,1,44.764500,-111.088000,17.661615,3.296971,...,0.000947,0.014268,0.000811,0.011236,0.000681,0.008840,0.000565,0.006971,0.000465,0.005524
3,60000622,10000503,WY,MCID,EHZ,1,44.764500,-111.088000,64.245602,6.698827,...,0.000124,0.004687,0.000104,0.003578,0.000087,0.002749,0.000072,0.002131,0.000060,0.001668
4,60001352,10001242,WY,YPP,EHZ,1,44.389333,-111.035833,22.657051,305.555989,...,0.002538,0.070311,0.002137,0.055708,0.001774,0.044119,0.001463,0.034991,0.001204,0.027859
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92290,60557152,10868795,WY,YFT,HHZ,1,44.586167,-111.097000,25.605611,305.905750,...,0.000426,0.006737,0.000351,0.006976,0.000294,0.006962,0.000250,0.006718,0.000215,0.006328
92291,60557152,10868797,WY,YHL,HHZ,1,44.586167,-111.097000,30.197630,166.928923,...,0.000186,0.010731,0.000171,0.009503,0.000158,0.008401,0.000145,0.007405,0.000134,0.006515
92292,60557152,10868800,WY,YNR,HHZ,1,44.586167,-111.097000,36.125928,246.704059,...,0.001069,0.020039,0.001022,0.021774,0.000952,0.022162,0.000863,0.021375,0.000768,0.019808
92293,60557152,10868799,WY,YML,EHZ,1,44.586167,-111.097000,36.096603,266.777241,...,0.000527,0.007680,0.000436,0.006279,0.000364,0.005106,0.000306,0.004143,0.000260,0.003363
92294,60557152,10868803,WY,YMV,HHZ,1,44.586167,-111.097000,53.832697,217.020959,...,0.001780,0.027440,0.001510,0.023214,0.001297,0.019335,0.001131,0.015981,0.000996,0.013158

In [4]:
old_p_feats.columns

Index(['arrival_identifier', 'avg_noise_1.00', 'avg_noise_10.00',
       'avg_noise_11.00', 'avg_noise_12.00', 'avg_noise_13.00',
       'avg_noise_14.00', 'avg_noise_15.00', 'avg_noise_16.00',
       'avg_noise_17.00', 'avg_noise_18.00', 'avg_noise_2.00',
       'avg_noise_3.00', 'avg_noise_4.00', 'avg_noise_5.00', 'avg_noise_6.00',
       'avg_noise_7.00', 'avg_noise_8.00', 'avg_noise_9.00', 'avg_signal_1.00',
       'avg_signal_10.00', 'avg_signal_11.00', 'avg_signal_12.00',
       'avg_signal_13.00', 'avg_signal_14.00', 'avg_signal_15.00',
       'avg_signal_16.00', 'avg_signal_17.00', 'avg_signal_18.00',
       'avg_signal_2.00', 'avg_signal_3.00', 'avg_signal_4.00',
       'avg_signal_5.00', 'avg_signal_6.00', 'avg_signal_7.00',
       'avg_signal_8.00', 'avg_signal_9.00', 'channel', 'event_identifier',
       'location_code', 'magnitude', 'magnitude_type', 'network',
       'noise_dominant_amplitude', 'noise_dominant_frequency',
       'noise_maximum_value', 'noise_minimum_value', 'noise_variance',
       'signal_dominant_amplitude', 'signal_dominant_frequency',
       'signal_maximum_value', 'signal_minimum_value', 'signal_variance',
       'source_depth_km', 'source_latitude', 'source_longitude',
       'source_receiver_back_azimuth', 'source_receiver_distance_km',
       'station'],
      dtype='object')

In [5]:
assert old_p_feats.columns.shape == new_p_feats.columns.shape, "Number of columns are different"
assert np.all(np.isin(new_p_feats.columns, old_p_feats.columns)), "Column names in New df are different"

Arrival IDs are very different

In [6]:
old_p_feats['arrival_identifier'].describe().loc[['min', 'max']]

min       2809.0
max    3990854.0
Name: arrival_identifier, dtype: float64

In [7]:
new_p_feats['arrival_identifier'].describe().loc[['min', 'max']]

min    10000491.0
max    10870349.0
Name: arrival_identifier, dtype: float64

Look at arrivals in the features

In [8]:
new_p_arrs = new_p_feats[['event_identifier', 'station', 'channel']]

In [9]:
old_p_arrs = old_p_feats[['event_identifier', 'station', 'channel']]

In [10]:
merge_arrs = new_p_arrs.merge(old_p_arrs, how='outer', suffixes=("_new", "old"), indicator=True)

In [11]:
print(f"{(merge_arrs['_merge'] == 'right_only').sum()} arrivals are only in the old file")
merge_arrs[merge_arrs['_merge'] == 'right_only']

1 arrivals are only in the old file

       event_identifier station channel      _merge
92295          60501597     YML     EHZ  right_only

In [12]:
print(f"{(merge_arrs['_merge'] == 'left_only').sum()} arrivals are only in the new file")
new_only_evids = merge_arrs[merge_arrs['_merge'] == 'left_only']['event_identifier'].drop_duplicates()
print(f"{len(new_only_evids)} evids are in the new file")

16804 arrivals are only in the new file
1386 evids are in the new file

In [13]:
print(f"{(merge_arrs['_merge'] == 'both').sum()} arrivals are in both files")
matching_events = merge_arrs[merge_arrs['_merge'] == 'both']['event_identifier'].drop_duplicates()
print(f"{len(matching_events)} evids are in both files")

75491 arrivals are in both files
6612 evids are in both files

In [14]:
dup_events = new_only_evids.iloc[np.where(np.isin(new_only_evids, matching_events))[0]]
print(f"{len(dup_events)} events that are in both catalogs but have additional arrivals in the new catalog")
merge_arrs[(merge_arrs.event_identifier.isin(dup_events)) & (merge_arrs['_merge'] == 'left_only')]

2 events that are in both catalogs but have additional arrivals in the new catalog

       event_identifier station channel     _merge
48271          60061312    B950     EHZ  left_only
48285          60061317    B950     EHZ  left_only

Look at the cause of new events in new file

In [15]:
# make assumption that largest evid corresponds to the most recent event in the catalog
old_p_max_evid = old_p_arrs['event_identifier'].max()

In [16]:
new_only_ev_df = new_p_feats[new_p_feats.event_identifier.isin(new_only_evids)][['event_identifier', 'source_longitude', 'source_latitude', 'source_depth_km']].drop_duplicates('event_identifier')

In [17]:
print(f"{new_only_ev_df[new_only_ev_df.event_identifier > old_p_max_evid].shape[0]}/{len(new_only_evids)} occur after the newest event in the old file")
new_only_ev_df[new_only_ev_df.event_identifier > old_p_max_evid]['source_longitude'].describe().loc[['min', 'max']]

1139/1386 occur after the newest event in the old file

min   -111.270667
max   -110.010833
Name: source_longitude, dtype: float64

In [18]:
print(f"{new_only_ev_df[(new_only_ev_df.event_identifier <= old_p_max_evid) & (new_only_ev_df.source_longitude <= -111.133)].shape[0]}/{len(new_only_evids)} occur on/before the newest event in the old file but west of -111.133")

245/1386 occur on/before the newest event in the old file but west of -111.133

In [19]:
print("The other events are those that contain additional arrivals in the new catalog")
new_only_ev_df[((new_only_ev_df.event_identifier < old_p_max_evid) & (new_only_ev_df.source_longitude > -111.133))]

The other events are those that contain additional arrivals in the new catalog

      event_identifier  source_longitude  source_latitude  source_depth_km
7393          60061312       -110.771500        44.799667             4.05
7399          60061317       -110.772667        44.808000             4.32

Compare feature information for matching arrivals between the catalog

In [20]:
merge_arrs[merge_arrs['_merge'] == 'both']

       event_identifier station channel _merge
0              60000622     YHB     EHZ   both
1              60000622     YDC     EHZ   both
2              60000622     YWB     EHZ   both
3              60000622    MCID     EHZ   both
4              60001352     YPP     EHZ   both
...                 ...     ...     ...    ...
83284          60507132     YNM     HHZ   both
83285          60507132     YML     EHZ   both
83286          60507132     YHH     HHZ   both
83287          60507132     YMC     EHZ   both
83288          60507132     YNE     HHZ   both

[75491 rows x 4 columns]

In [21]:
# Columns names so cols can be in the same order and remove arrival id
cols = ['event_identifier', 'network', 'station',
       'channel', 'location_code', 'source_latitude', 'source_longitude',
       'source_receiver_distance_km', 'source_receiver_back_azimuth',
       'source_depth_km', 'noise_variance', 'noise_minimum_value',
       'noise_maximum_value', 'signal_variance', 'signal_minimum_value',
       'signal_maximum_value', 'noise_dominant_frequency',
       'noise_dominant_amplitude', 'signal_dominant_frequency',
       'signal_dominant_amplitude', 'magnitude_type', 'magnitude',
       'avg_noise_1.00', 'avg_signal_1.00', 'avg_noise_2.00',
       'avg_signal_2.00', 'avg_noise_3.00', 'avg_signal_3.00',
       'avg_noise_4.00', 'avg_signal_4.00', 'avg_noise_5.00',
       'avg_signal_5.00', 'avg_noise_6.00', 'avg_signal_6.00',
       'avg_noise_7.00', 'avg_signal_7.00', 'avg_noise_8.00',
       'avg_signal_8.00', 'avg_noise_9.00', 'avg_signal_9.00',
       'avg_noise_10.00', 'avg_signal_10.00', 'avg_noise_11.00',
       'avg_signal_11.00', 'avg_noise_12.00', 'avg_signal_12.00',
       'avg_noise_13.00', 'avg_signal_13.00', 'avg_noise_14.00',
       'avg_signal_14.00', 'avg_noise_15.00', 'avg_signal_15.00',
       'avg_noise_16.00', 'avg_signal_16.00', 'avg_noise_17.00',
       'avg_signal_17.00', 'avg_noise_18.00', 'avg_signal_18.00']

In [22]:
old_p_matching_feats_df = old_p_feats.merge(merge_arrs[merge_arrs['_merge'] == 'both'][['event_identifier', 'station', 'channel']], how='inner').sort_values(['event_identifier', 'station', 'channel']).reset_index(drop=True)[cols]
print(old_p_matching_feats_df.shape)
old_p_matching_feats_df.head()

(75491, 58)

,event_identifier,network,station,channel,location_code,source_latitude,source_longitude,source_receiver_distance_km,source_receiver_back_azimuth,source_depth_km,...,avg_noise_14.00,avg_signal_14.00,avg_noise_15.00,avg_signal_15.00,avg_noise_16.00,avg_signal_16.00,avg_noise_17.00,avg_signal_17.00,avg_noise_18.00,avg_signal_18.00
0,60000622,PB,B207,EHZ,1,44.7645,-111.088,24.936949,310.504241,7.69,...,0.000201,0.003299,0.000224,0.003135,0.000235,0.002923,0.000232,0.002703,0.000219,0.002505
1,60000622,WY,MCID,EHZ,1,44.7645,-111.088,64.245602,6.698827,7.69,...,0.000124,0.004687,0.000104,0.003578,0.000087,0.002749,0.000072,0.002131,0.000060,0.001668
2,60000622,WY,YDC,EHZ,1,44.7645,-111.088,13.478685,62.981132,7.69,...,0.001299,0.029062,0.001054,0.022419,0.000852,0.017364,0.000688,0.013535,0.000557,0.010637
3,60000622,WY,YHB,EHZ,1,44.7645,-111.088,8.701337,79.885217,7.69,...,0.000567,0.048452,0.000471,0.037601,0.000394,0.029268,0.000327,0.022911,0.000270,0.018074
4,60000622,WY,YHH,HHZ,1,44.7645,-111.088,18.984408,262.065224,7.69,...,0.000219,0.022251,0.000231,0.020611,0.000265,0.018673,0.000304,0.016737,0.000336,0.015046

In [23]:
new_p_matching_feats_df = new_p_feats.merge(merge_arrs[merge_arrs['_merge'] == 'both'][['event_identifier', 'station', 'channel']], how='inner').sort_values(['event_identifier', 'station', 'channel']).reset_index(drop=True)[cols]
print(new_p_matching_feats_df.shape)
new_p_matching_feats_df.head()

(75491, 58)

,event_identifier,network,station,channel,location_code,source_latitude,source_longitude,source_receiver_distance_km,source_receiver_back_azimuth,source_depth_km,...,avg_noise_14.00,avg_signal_14.00,avg_noise_15.00,avg_signal_15.00,avg_noise_16.00,avg_signal_16.00,avg_noise_17.00,avg_signal_17.00,avg_noise_18.00,avg_signal_18.00
0,60000622,PB,B207,EHZ,1,44.7645,-111.088,24.936949,310.504241,7.69,...,0.000201,0.003299,0.000224,0.003135,0.000235,0.002923,0.000232,0.002703,0.000219,0.002505
1,60000622,WY,MCID,EHZ,1,44.7645,-111.088,64.245602,6.698827,7.69,...,0.000124,0.004687,0.000104,0.003578,0.000087,0.002749,0.000072,0.002131,0.000060,0.001668
2,60000622,WY,YDC,EHZ,1,44.7645,-111.088,13.478685,62.981132,7.69,...,0.001299,0.029062,0.001054,0.022419,0.000852,0.017364,0.000688,0.013535,0.000557,0.010637
3,60000622,WY,YHB,EHZ,1,44.7645,-111.088,8.701337,79.885217,7.69,...,0.000567,0.048452,0.000471,0.037601,0.000394,0.029268,0.000327,0.022911,0.000270,0.018074
4,60000622,WY,YHH,HHZ,1,44.7645,-111.088,18.984408,262.065224,7.69,...,0.000219,0.022251,0.000231,0.020611,0.000265,0.018673,0.000304,0.016737,0.000336,0.015046

In [25]:
atol = 0.1
inds = []
for col in cols:
    s_new = new_p_matching_feats_df[col].values
    s_old = old_p_matching_feats_df[col].values
    arr_eq = np.array_equal(s_new, s_old)
    # print(col, arr_eq)
    if not arr_eq:
        print(col)
        print("\tAll close:", np.allclose(s_new, s_old, rtol=1e-2))
        print(f"\t{np.not_equal(s_new, s_old).sum()}/{len(s_new)} elements are different, {(abs(s_new-s_old) > atol).sum()} are > {atol}")
        print(f"\taverage difference: {np.mean(s_new-s_old):0.2e}, std: {np.std(s_new-s_old):0.2e}, abs max: {np.max(abs(s_new-s_old)):0.2e}")
        inds.append(np.where(abs(s_new-s_old) > atol)[0])
inds = np.unique(np.concatenate(inds))
print(f"{inds.shape[0]} with some difference > {atol}")

source_latitude
	All close: True
	3562/75491 elements are different, 0 are > 0.1
	average difference: 6.18e-07, std: 5.37e-05, abs max: 4.67e-03
source_longitude
	All close: True
	17248/75491 elements are different, 0 are > 0.1
	average difference: 1.46e-06, std: 1.27e-04, abs max: 1.10e-02
source_receiver_distance_km
	All close: False
	51801/75491 elements are different, 10 are > 0.1
	average difference: 1.20e-04, std: 1.05e-02, abs max: 1.01e+00
source_receiver_back_azimuth
	All close: False
	53984/75491 elements are different, 10 are > 0.1
	average difference: 1.87e-06, std: 9.42e-03, abs max: 1.48e+00
source_depth_km
	All close: False
	10/75491 elements are different, 10 are > 0.1
	average difference: 3.31e-05, std: 2.88e-03, abs max: 2.50e-01
noise_variance
	All close: False
	6463/75491 elements are different, 0 are > 0.1
	average difference: 4.30e-05, std: 1.00e-03, abs max: 9.73e-02
noise_minimum_value
	All close: False
	18600/75491 elements are different, 73 are > 0.1
	average difference: -3.56e-04, std: 5.94e-03, abs max: 3.27e-01
noise_maximum_value
	All close: False
	18578/75491 elements are different, 68 are > 0.1
	average difference: 3.56e-04, std: 5.94e-03, abs max: 3.64e-01
signal_variance
	All close: False
	15828/75491 elements are different, 185 are > 0.1
	average difference: 4.05e-02, std: 5.32e+00, abs max: 1.38e+03
signal_minimum_value
	All close: False
	23933/75491 elements are different, 371 are > 0.1
	average difference: -8.12e-03, std: 2.96e-01, abs max: 4.28e+01
signal_maximum_value
	All close: False
	24109/75491 elements are different, 370 are > 0.1
	average difference: 9.14e-03, std: 3.88e-01, abs max: 7.48e+01
noise_dominant_amplitude
	All close: False
	4289/75491 elements are different, 2 are > 0.1
	average difference: 2.69e-05, std: 8.87e-04, abs max: 1.24e-01
signal_dominant_amplitude
	All close: False
	6973/75491 elements are different, 23 are > 0.1
	average difference: 1.59e-04, std: 6.58e-03, abs max: 1.27e+00
avg_noise_1.00
	All close: False
	19366/75491 elements are different, 1 are > 0.1
	average difference: 1.96e-05, std: 6.83e-04, abs max: 1.05e-01
avg_signal_1.00
	All close: False
	23929/75491 elements are different, 13 are > 0.1
	average difference: 1.42e-04, std: 9.90e-03, abs max: 2.18e+00
avg_noise_2.00
	All close: False
	10942/75491 elements are different, 2 are > 0.1
	average difference: 2.29e-05, std: 7.80e-04, abs max: 1.27e-01
avg_signal_2.00
	All close: False
	21326/75491 elements are different, 31 are > 0.1
	average difference: 3.12e-04, std: 2.57e-02, abs max: 6.22e+00
avg_noise_3.00
	All close: False
	5757/75491 elements are different, 1 are > 0.1
	average difference: 1.96e-05, std: 6.15e-04, abs max: 1.04e-01
avg_signal_3.00
	All close: False
	17331/75491 elements are different, 47 are > 0.1
	average difference: 3.84e-04, std: 2.64e-02, abs max: 6.16e+00
avg_noise_4.00
	All close: False
	3726/75491 elements are different, 0 are > 0.1
	average difference: 1.63e-05, std: 4.54e-04, abs max: 7.15e-02
avg_signal_4.00
	All close: False
	14375/75491 elements are different, 52 are > 0.1
	average difference: 3.60e-04, std: 1.74e-02, abs max: 3.39e+00
avg_noise_5.00
	All close: False
	2814/75491 elements are different, 0 are > 0.1
	average difference: 1.30e-05, std: 3.38e-04, abs max: 4.20e-02
avg_signal_5.00
	All close: False
	12099/75491 elements are different, 71 are > 0.1
	average difference: 4.41e-04, std: 1.70e-02, abs max: 2.73e+00
avg_noise_6.00
	All close: False
	2412/75491 elements are different, 0 are > 0.1
	average difference: 9.73e-06, std: 2.44e-04, abs max: 3.05e-02
avg_signal_6.00
	All close: False
	10716/75491 elements are different, 86 are > 0.1
	average difference: 5.78e-04, std: 2.27e-02, abs max: 3.98e+00
avg_noise_7.00
	All close: False
	2137/75491 elements are different, 0 are > 0.1
	average difference: 7.08e-06, std: 1.75e-04, abs max: 2.23e-02
avg_signal_7.00
	All close: False
	9609/75491 elements are different, 87 are > 0.1
	average difference: 6.23e-04, std: 2.53e-02, abs max: 4.65e+00
avg_noise_8.00
	All close: False
	1986/75491 elements are different, 0 are > 0.1
	average difference: 5.25e-06, std: 1.30e-04, abs max: 1.56e-02
avg_signal_8.00
	All close: False
	8715/75491 elements are different, 84 are > 0.1
	average difference: 5.94e-04, std: 2.43e-02, abs max: 4.47e+00
avg_noise_9.00
	All close: False
	1826/75491 elements are different, 0 are > 0.1
	average difference: 4.11e-06, std: 1.02e-04, abs max: 1.04e-02
avg_signal_9.00
	All close: False
	8220/75491 elements are different, 81 are > 0.1
	average difference: 5.37e-04, std: 2.17e-02, abs max: 3.89e+00
avg_noise_10.00
	All close: False
	1765/75491 elements are different, 0 are > 0.1
	average difference: 3.53e-06, std: 8.71e-05, abs max: 1.09e-02
avg_signal_10.00
	All close: False
	7889/75491 elements are different, 75 are > 0.1
	average difference: 4.76e-04, std: 1.91e-02, abs max: 3.29e+00
avg_noise_11.00
	All close: False
	1631/75491 elements are different, 0 are > 0.1
	average difference: 3.93e-06, std: 8.40e-05, abs max: 1.09e-02
avg_signal_11.00
	All close: False
	7543/75491 elements are different, 70 are > 0.1
	average difference: 4.19e-04, std: 1.67e-02, abs max: 2.72e+00
avg_noise_12.00
	All close: False
	1597/75491 elements are different, 0 are > 0.1
	average difference: 6.25e-06, std: 1.10e-04, abs max: 1.07e-02
avg_signal_12.00
	All close: False
	7216/75491 elements are different, 65 are > 0.1
	average difference: 3.73e-04, std: 1.46e-02, abs max: 2.23e+00
avg_noise_13.00
	All close: False
	1600/75491 elements are different, 0 are > 0.1
	average difference: 1.03e-05, std: 1.70e-04, abs max: 1.06e-02
avg_signal_13.00
	All close: False
	6850/75491 elements are different, 61 are > 0.1
	average difference: 3.40e-04, std: 1.29e-02, abs max: 1.92e+00
avg_noise_14.00
	All close: False
	1553/75491 elements are different, 0 are > 0.1
	average difference: 1.48e-05, std: 2.41e-04, abs max: 1.02e-02
avg_signal_14.00
	All close: False
	6767/75491 elements are different, 53 are > 0.1
	average difference: 3.17e-04, std: 1.15e-02, abs max: 1.74e+00
avg_noise_15.00
	All close: False
	1627/75491 elements are different, 0 are > 0.1
	average difference: 1.85e-05, std: 3.00e-04, abs max: 1.18e-02
avg_signal_15.00
	All close: False
	6411/75491 elements are different, 50 are > 0.1
	average difference: 2.97e-04, std: 1.03e-02, abs max: 1.54e+00
avg_noise_16.00
	All close: False
	1711/75491 elements are different, 0 are > 0.1
	average difference: 2.07e-05, std: 3.35e-04, abs max: 1.31e-02
avg_signal_16.00
	All close: False
	6247/75491 elements are different, 43 are > 0.1
	average difference: 2.75e-04, std: 9.15e-03, abs max: 1.34e+00
avg_noise_17.00
	All close: False
	1974/75491 elements are different, 0 are > 0.1
	average difference: 2.14e-05, std: 3.46e-04, abs max: 1.34e-02
avg_signal_17.00
	All close: False
	5823/75491 elements are different, 38 are > 0.1
	average difference: 2.52e-04, std: 8.07e-03, abs max: 1.15e+00
avg_noise_18.00
	All close: False
	2130/75491 elements are different, 0 are > 0.1
	average difference: 2.08e-05, std: 3.37e-04, abs max: 1.30e-02
avg_signal_18.00
	All close: False
	5535/75491 elements are different, 36 are > 0.1
	average difference: 2.27e-04, std: 7.06e-03, abs max: 9.86e-01
383 with some difference > 0.1

In [26]:
print(f"Station breakdown of arrivals with some feature difference > {atol}:")
old_p_matching_feats_df.loc[inds][['station', 'channel']].value_counts()

Station breakdown of arrivals with some feature difference > 0.1:

station  channel
YHB      HHZ        374
MCID     EHZ          1
YFT      HHZ          1
YGC      EHZ          1
YHH      HHZ          1
YHL      HHZ          1
YMC      EHZ          1
YMR      HHZ          1
YPM      EHZ          1
YWB      EHZ          1
Name: count, dtype: int64

In [27]:
bad_evids = old_p_matching_feats_df.iloc[inds].event_identifier.value_counts().reset_index()
print(f"{len(bad_evids)} events with > {atol} difference in some feature")

374 events with > 0.1 difference in some feature

In [28]:
bad_evids

     event_identifier  count
0            60501597     10
1            60485367      1
2            60478722      1
3            60477752      1
4            60477322      1
..                ...    ...
369          60442682      1
370          60442677      1
371          60442672      1
372          60442612      1
373          60442877      1

[374 rows x 2 columns]

Some specifics

In [29]:
# One event seems to account for all non-YHB differences
# Event location seems to have changed 
compare_df = new_p_matching_feats_df[new_p_matching_feats_df.event_identifier == bad_evids[bad_evids["count"] > 1].event_identifier.values[0]].compare(old_p_matching_feats_df[old_p_matching_feats_df.event_identifier == bad_evids[bad_evids["count"] > 1].event_identifier.values[0]])
compare_df

      source_latitude            source_longitude           \
                 self      other             self    other
75109          44.824  44.819333         -110.743 -110.754
75110          44.824  44.819333         -110.743 -110.754
75111          44.824  44.819333         -110.743 -110.754
75112          44.824  44.819333         -110.743 -110.754
75113          44.824  44.819333         -110.743 -110.754
75114          44.824  44.819333         -110.743 -110.754
75115          44.824  44.819333         -110.743 -110.754
75116          44.824  44.819333         -110.743 -110.754
75117          44.824  44.819333         -110.743 -110.754
75118          44.824  44.819333         -110.743 -110.754

      source_receiver_distance_km            source_receiver_back_azimuth  \
                             self      other                         self
75109                   78.616206  77.765289                    26.251010
75110                   42.062701  41.406461                    10.052099
75111                   28.921157  28.004824                    83.733254
75112                   36.776152  35.815239                    77.061472
75113                    9.382984   8.376037                    64.972135
75114                   34.918710  34.103025                    94.755899
75115                   22.029577  21.039339                    70.867450
75116                   24.638307  23.655067                    45.447662
75117                   21.042153  20.180061                    28.186080
75118                   37.305454  36.307224                    49.341083

                 source_depth_km        ... avg_signal_16.00            \
           other            self other  ...             self     other
75109  25.848442            8.55   8.3  ...              NaN       NaN
75110   8.992892            8.55   8.3  ...              NaN       NaN
75111  84.601969            8.55   8.3  ...              NaN       NaN
75112  77.566909            8.55   8.3  ...          0.05765  0.037308
75113  65.677464            8.55   8.3  ...              NaN       NaN
75114  95.752824            8.55   8.3  ...              NaN       NaN
75115  71.433767            8.55   8.3  ...              NaN       NaN
75116  44.870748            8.55   8.3  ...              NaN       NaN
75117  26.707817            8.55   8.3  ...              NaN       NaN
75118  49.074192            8.55   8.3  ...              NaN       NaN

      avg_noise_17.00           avg_signal_17.00           avg_noise_18.00  \
                 self     other             self     other            self
75109             NaN       NaN              NaN       NaN             NaN
75110             NaN       NaN              NaN       NaN             NaN
75111             NaN       NaN              NaN       NaN             NaN
75112        0.004992  0.003231         0.053861  0.034856        0.004901
75113             NaN       NaN              NaN       NaN             NaN
75114             NaN       NaN              NaN       NaN             NaN
75115             NaN       NaN              NaN       NaN             NaN
75116             NaN       NaN              NaN       NaN             NaN
75117             NaN       NaN              NaN       NaN             NaN
75118             NaN       NaN              NaN       NaN             NaN

                avg_signal_18.00
          other             self    other
75109       NaN              NaN      NaN
75110       NaN              NaN      NaN
75111       NaN              NaN      NaN
75112  0.003172         0.048999  0.03171
75113       NaN              NaN      NaN
75114       NaN              NaN      NaN
75115       NaN              NaN      NaN
75116       NaN              NaN      NaN
75117       NaN              NaN      NaN
75118       NaN              NaN      NaN

[10 rows x 98 columns]

In [30]:
# All differences in features at this event are at station YHB
np.unique(np.where(~np.isnan(compare_df[['noise_variance', 'noise_minimum_value',
       'noise_maximum_value', 'signal_variance', 'signal_minimum_value',
       'signal_maximum_value',
       'noise_dominant_amplitude',
       'signal_dominant_amplitude',
       'avg_noise_1.00', 'avg_signal_1.00', 'avg_noise_2.00',
       'avg_signal_2.00', 'avg_noise_3.00', 'avg_signal_3.00',
       'avg_noise_4.00', 'avg_signal_4.00', 'avg_noise_5.00',
       'avg_signal_5.00', 'avg_noise_6.00', 'avg_signal_6.00',
       'avg_noise_7.00', 'avg_signal_7.00', 'avg_noise_8.00',
       'avg_signal_8.00', 'avg_noise_9.00', 'avg_signal_9.00',
       'avg_noise_10.00', 'avg_signal_10.00', 'avg_noise_11.00',
       'avg_signal_11.00', 'avg_noise_12.00', 'avg_signal_12.00',
       'avg_noise_13.00', 'avg_signal_13.00', 'avg_noise_14.00',
       'avg_signal_14.00', 'avg_noise_15.00', 'avg_signal_15.00',
       'avg_noise_16.00', 'avg_signal_16.00', 'avg_noise_17.00',
       'avg_signal_17.00', 'avg_noise_18.00', 'avg_signal_18.00']].values))[0])

array([3])

In [31]:
# Events seem to be from 10/2020 - 7/2022 
bad_evids[bad_evids['count'] < 10].describe().loc[['min', 'max']]

     event_identifier  count
min        60413457.0    1.0
max        60506742.0    1.0

In [32]:
# Number of arrivals at YHB.HHZ in both catalogs
merge_arrs[(merge_arrs.station == 'YHB') & (merge_arrs._merge == 'both') & (merge_arrs.channel == 'HHZ')].shape[0]

1458

In [36]:
# Number of arrivals at YHB.HHZ in both catalogs before 60413457 (smallest evid with discrepancy)
merge_arrs[(merge_arrs.station == 'YHB') & (merge_arrs._merge == 'both') & (merge_arrs.channel == 'HHZ') & (merge_arrs.event_identifier < 60413457)].shape[0]

1075

In [34]:
# None after 60506742, which is the largest evid with the discrepancy
merge_arrs[(merge_arrs.station == 'YHB') & (merge_arrs._merge == 'both') & (merge_arrs.channel == 'HHZ') & (merge_arrs.event_identifier > 60506742.0)].shape[0]

0

In [37]:
print(f"{1458 - 1075 - 374} arrivals at YHB.HHZ without discrepancy after 60413457")

9 arrivals at YHB.HHZ without discrepancy after 60413457

There must be some change in the metadata at station YHB.HHZ after ~10/2020 between when I made my catalog and Ben made his (a while ago). Going to go with the new values because seems possible something got updated and is hopefully better now.

In [66]:
new_p_matching_feats_df.loc[inds, ['signal_maximum_value', 'noise_maximum_value', 'avg_signal_1.00', 'signal_variance', 'signal_dominant_amplitude']].describe()

,signal_maximum_value,noise_maximum_value,avg_signal_1.00,signal_variance,signal_dominant_amplitude
count,383.000000,383.000000,383.000000,383.000000,383.000000
mean,5.322104,0.197596,0.080796,14.066420,0.091787
std,14.955349,0.129318,0.386442,128.165080,0.248887
min,0.187952,0.009650,0.001407,0.006628,0.003378
25%,0.728571,0.115748,0.009876,0.045068,0.012781
50%,1.532920,0.165348,0.017526,0.167214,0.026294
75%,4.249017,0.249642,0.041047,0.993188,0.070871
max,211.938126,1.032528,6.183221,2367.177771,3.599383

In [67]:
old_p_matching_feats_df.loc[inds, ['signal_maximum_value', 'noise_maximum_value', 'avg_signal_1.00', 'signal_variance', 'signal_dominant_amplitude']].describe()

,signal_maximum_value,noise_maximum_value,avg_signal_1.00,signal_variance,signal_dominant_amplitude
count,383.000000,383.000000,383.000000,383.000000,383.000000
mean,3.522475,0.128187,0.052789,6.089790,0.060413
std,10.016520,0.083349,0.250268,53.950188,0.163454
min,0.146857,0.009650,0.000910,0.002776,0.002186
25%,0.476675,0.074906,0.006464,0.018875,0.008313
50%,1.006966,0.107005,0.011484,0.071849,0.017134
75%,2.760172,0.161556,0.027274,0.415950,0.046640
max,137.155740,0.668200,4.001471,991.381175,2.329340